basic:
    name: Escs
    environments:
        production: 'https://www.escs.ipl.pt/'
        staging: 'https://iplescs.dev11.javali.pt/'
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: dev11, password: dev11 }
        development: { user: '', password: '' }
    breakpoints:
        - 375
        - 640
        - 1024
        - 1366
    pages:
        - /
        - /home
        - /en/home
        - /user/login
        - /user/register
        - /escola/missao-e-valores
        - /escola/historia-e-memoria
        - /escola/orgaos-de-governo/conselho-de-representantes
        - /escola/orgaos-de-governo/presidente
        - /escola/orgaos-de-governo/conselho-tecnico-cientifico
        - /escola/orgaos-de-governo/conselho-pedagogico
        - /escola/servicos/biblioteca
        - /escola/servicos/servicos-tecnico-administrativos/recursos-humanos
        - /escola/servicos/secretaria/servicos-academicos
        - /escola/servicos/secretaria/tesouraria
        - /escola/servicos/sape
        - /escola/servicos/servicos-de-audiovisual
        - /escola/servicos/servico-de-comunicacao
        - /escola/servicos/servicos-multimedia
        - /escola/servicos/servicos-tecnico-administrativos/contabilidade
        - /escola/servicos/servicos-tecnico-administrativos/manutencao
        - /escola/gabinetes/alumni
        - /escola/gabinetes/gabinete-de-apoio-a-investigacao
        - /escola/gabinetes/gabinete-de-apoio-a-qualidade
        - /escola/gabinetes/gabinete-de-estagios
        - /escola/gabinetes/gabinete-de-relacoes-internacionais
        - /escola/gabinetes/nucleo-de-informatica
        - /escola/departamentos/audiovisual-e-multimedia
        - /escola/departamentos/ciencias-da-comunicacao
        - /escola/departamentos/ciencias-humanas
        - /escola/departamentos/ciencias-sociais
        - /escola/departamentos/estatistica
        - /escola/departamentos/media-e-jornalismo
        - /escola/departamentos/publicidade-e-marketing
        - /escola/departamentos/relacoes-publicas-e-comunicacao-organizacional
        - /escola/areas-tecnologicas
        - /cursos/licenciaturas/audiovisual-e-multimedia
        - /cursos/licenciaturas/jornalismo
        - /cursos/licenciaturas/publicidade-e-marketing
        - /cursos/licenciaturas/relacoes-publicas-e-comunicacao-empresarial
        - /cursos/mestrados/audiovisual-e-multimedia
        - /cursos/mestrados/gestao-estrategica-das-relacoes-publicas
        - /cursos/mestrados/jornalismo
        - /cursos/mestrados/publicidade-e-marketing
        - /cursos/pos-graduacoes/branding-e-content-marketing
        - /cursos/pos-graduacoes/comunicacao-corporativa-sustentabilidade-e-cidadania
        - /cursos/pos-graduacoes/comunicacao-e-marketing-na-industria-farmaceutica
        - /cursos/pos-graduacoes/industrias-criativas-gestao-e-tendencias
        - /cursos/pos-graduacoes/jornalismo-desportivo
        - /cursos/pos-graduacoes/storytelling
        - /cursos/disciplinas-lecionadas-em-ingles
        - /cursos/curso-de-especializacao/marketing-e-data-science
        - /investigacao/liacom
        - /investigacao/projetos-de-investigacao/linha-1
        - /investigacao/projetos-de-investigacao/linha-2
        - /investigacao/ceic
        - /investigacao/revista-comunicacao-publica
        - /investigacao/podcast-cienciacom
        - /investigacao/icml
        - /investigacao/programa-de-pos-doutoramento
        - /internacional/mobilidade-alunos/erasmus
        - /internacional/mobilidade-alunos/intercambio-fora-da-europa
        - /internacional/mobilidade-alunos/faq
        - /internacional/mobilidade-staff/docentes
        - /internacional/mobilidade-staff/nao-docentes
        - /internacional/estudante-internacional
        - /internacional/redes-id
        - /comunidade/protocolos
        - /comunidade/projetos-com-a-sociedade
        - /comunidade/sustentabilidade
        - /comunidade/voluntariado
        - /comunidade/clube-de-leitura-entrelinhas
        - /alunos/informacao-academica
        - /alunos/associacao-de-estudantes
        - /alunos/e2
        - /alunos/revista-narrativas
        - /alunos/prlab
        - /alunos/bright-lisbon-agency
        - /alunos/escstunis
        - /alunos/extracurriculares/escs-fm
        - /alunos/extracurriculares/escs-magazine
        - /alunos/extracurriculares/escs-mais-limpa
        - /alunos/extracurriculares/game
        - /alunos/extracurriculares/nav
        - /alunos/extracurriculares/numero-f
        - /alunos/extracurriculares/pancadas-do-infinito
        - /alunos/empreendedorismo
        - /alunos/programa-mentoria-interpares-ipl-escs
        - /alunos/bolsas-de-estudo-prr
        - /candidatos/matriculas
        - /candidatos/concursos-especiais/maiores-23-anos
        - /candidatos/concursos-especiais/titulares-det
        - /candidatos/concursos-especiais/titulares-dtsp
        - /candidatos/concursos-especiais/titulares-ocs
        - /candidatos/mudanca-de-par-instituicao-curso
        - /candidatos/necessidades-educativas-especiais
        - /editoriais/escs-lanca-primeiro-mooc
        - /candidatos/mestrados
        - /candidatos/pos-graduacoes
        - /cursos/pos-graduacoes/marketing-e-data-science/candidaturas
        - /editoriais/liacom-acreditado-pela-fct
        - /artigos
        - /editoriais/escs-participa-no-projeto-businet-international-trade-mission-na-noruega
        - /editoriais/3a-edicao-do-programa-de-mentoring-am
        - /editoriais/finalistas-de-rpce-visitaram-lusa
        - /editoriais/um-mundo-de-oportunidades
        - /editoriais/estudantes-de-rpce-utilizam-ferramenta-da-carma
        - /eventos
        - /eventos/exibicao-de-filmes
        - /agenda-e-eventos/workshop-colab-games
        - /agenda-e-eventos/premio-de-jornalismo-de-dados-spe-3ed
        - /contactos
        - /faqs
        - /politica-de-privacidade
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 40
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: "(function () {\n  const banner = document.querySelector(\".eu-cookie-compliance-banner\");\n  if (banner) {\n    banner.style.display = \"none\";\n  }\n})();\n"
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
